# Generated by Django 4.2.4 on 2023-08-04 17:59

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ECG",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ECGLeadResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lead",
                    models.CharField(
                        choices=[
                            ("I", "I"),
                            ("II", "II"),
                            ("III", "III"),
                            ("aVR", "aVR"),
                            ("aVL", "aVL"),
                            ("aVF", "aVF"),
                            ("V1", "V1"),
                            ("V2", "V2"),
                            ("V3", "V3"),
                            ("V4", "V4"),
                            ("V5", "V5"),
                            ("V6", "V6"),
                        ]
                    ),
                ),
                (
                    "signal",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), size=None
                    ),
                ),
                ("num_samples", models.IntegerField(blank=True, null=True)),
                ("zero_crossing_count", models.IntegerField(blank=True, null=True)),
                (
                    "ecg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ecgs.ecg"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="ecgleadresult",
            constraint=models.UniqueConstraint(
                fields=("ecg", "lead"), name="unique_ecg_lead"
            ),
        ),
    ]
